version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_bot_spices_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  app:
#    image: telegram-bot-spices-shop:0.1
#    build:
#      context: .
#      dockerfile: Dockerfile
#    depends_on:
#      - postgres
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/online_store
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
  postgres_data:
    name: postgres